Use tito;

#####################################################################################
# Using the ID in the Where clause eliminates any "Safe Mode" protections
Delete From firms Where ID >= 0;

#####################################################################################

#firms
Insert Into firms (name) values ("​The Gokey Group, Inc");
Insert Into firms (name) values ("4M Research");
Insert Into firms (name) values ("7693125 Canada Inc");
Insert Into firms (name) values ("A.A.A Consulting Inc");
Insert Into firms (name) values ("Abacus IT Solutions Inc.");
Insert Into firms (name) values ("Accenture");
Insert Into firms (name) values ("ADDX");
Insert Into firms (name) values ("ADS IT Consulting");
Insert Into firms (name) values ("AdTech LLC");
Insert Into firms (name) values ("Agile Blue Technologies");
Insert Into firms (name) values ("Agile Software Group, LLC");
Insert Into firms (name) values ("Agility Consulting");
Insert Into firms (name) values ("Aiken Software");
Insert Into firms (name) values ("Aleroh Consulting Inc");
Insert Into firms (name) values ("Allegheny Consulting LLC");
Insert Into firms (name) values ("Amber Architects");
Insert Into firms (name) values ("American Strategic Planners, LLC");
Insert Into firms (name) values ("Amogh Consultants");
Insert Into firms (name) values ("Andwyrde");
Insert Into firms (name) values ("Apeiron Data");
Insert Into firms (name) values ("Apex Technology Solutions");
Insert Into firms (name) values ("Aptec");
Insert Into firms (name) values ("Armedia, LLC");
Insert Into firms (name) values ("Astute");
Insert Into firms (name) values ("Auxilium");
Insert Into firms (name) values ("AWS Consulting");
Insert Into firms (name) values ("AyStrive, Inc.");
Insert Into firms (name) values ("Bayforce");
Insert Into firms (name) values ("BBP Enterprises, LLC");
Insert Into firms (name) values ("BCC Solutions");
Insert Into firms (name) values ("Beamer Inc.");
Insert Into firms (name) values ("Bedrock Investments");
Insert Into firms (name) values ("BFS Group Inc");
Insert Into firms (name) values ("Bixal");
Insert Into firms (name) values ("Brandywine Enterprise Consulting LLC");
Insert Into firms (name) values ("Bridgephase");
Insert Into firms (name) values ("Bryant Warren Management Consultants");
Insert Into firms (name) values ("Buretsol LLC");
Insert Into firms (name) values ("Business Concepts Solutions");
Insert Into firms (name) values ("Canteq Consulting, LLC");
Insert Into firms (name) values ("CGI Federal");
Insert Into firms (name) values ("Charlotte DeVerner");
Insert Into firms (name) values ("Chawla Systems, Inc");
Insert Into firms (name) values ("Clearsoft");
Insert Into firms (name) values ("CMack Solutions");
Insert Into firms (name) values ("Commodore Information Technology");
Insert Into firms (name) values ("ComputeInfi");
Insert Into firms (name) values ("Computer Cosmos");
Insert Into firms (name) values ("Connected Logistics Inc");
Insert Into firms (name) values ("CSRA");
Insert Into firms (name) values ("Curotec");
Insert Into firms (name) values ("Cynthia Boatright LLC");
Insert Into firms (name) values ("Datature Inc.");
Insert Into firms (name) values ("Deosi LLC");
Insert Into firms (name) values ("Directrium LLC");
Insert Into firms (name) values ("DJN Integration Solutions LLC");
Insert Into firms (name) values ("DN Assoc Inc");
Insert Into firms (name) values ("DNS Analytics");
Insert Into firms (name) values ("DoubleQ Technologies, Inc.");
Insert Into firms (name) values ("DSRS LLC");
Insert Into firms (name) values ("Dynomag Corporation");
Insert Into firms (name) values ("EigenX, LLC");
Insert Into firms (name) values ("Ensode Technology, LLC");
Insert Into firms (name) values ("Enterprise Security Group");
Insert Into firms (name) values ("Ericsson");
Insert Into firms (name) values ("Executive Enterprises, Inc");
Insert Into firms (name) values ("Fern & Crall LLC");
Insert Into firms (name) values ("Fingertips");
Insert Into firms (name) values ("Finley Consulting");
Insert Into firms (name) values ("First Tier Technology LLC");
Insert Into firms (name) values ("Fluint LLC");
Insert Into firms (name) values ("Full Visibility");
Insert Into firms (name) values ("FuTech Corporation");
Insert Into firms (name) values ("Glen Gordon (sole proprietor)");
Insert Into firms (name) values ("Global Software Solutions Inc");
Insert Into firms (name) values ("Got SOA LLC");
Insert Into firms (name) values ("Greene Consulting, LLC");
Insert Into firms (name) values ("Greshko Consulting Inc");
Insert Into firms (name) values ("Guidance Consulting");
Insert Into firms (name) values ("Hayes Consulting");
Insert Into firms (name) values ("Hillside Technology");
Insert Into firms (name) values ("Hi-Tech Prosperity");
Insert Into firms (name) values ("HK-Technologies, Inc.");
Insert Into firms (name) values ("Hogan & Company, LLC");
Insert Into firms (name) values ("IBC");
Insert Into firms (name) values ("IForze LLC");
Insert Into firms (name) values ("Inastrol");
Insert Into firms (name) values ("InnovatIT");
Insert Into firms (name) values ("Innovative Mapping Solutions");
Insert Into firms (name) values ("Inseris");
Insert Into firms (name) values ("Integration Solution Partners");
Insert Into firms (name) values ("Interlink Consulting");
Insert Into firms (name) values ("Ireland Consulting, Inc");
Insert Into firms (name) values ("Iron Rock Consulting");
Insert Into firms (name) values ("IT Objects LLC");
Insert Into firms (name) values ("iTelligence Inc");
Insert Into firms (name) values ("IV Technologies");
Insert Into firms (name) values ("Ividix");
Insert Into firms (name) values ("JB Training Resources");
Insert Into firms (name) values ("Jempir Technology Solutions Inc.");
Insert Into firms (name) values ("John Henares");
Insert Into firms (name) values ("Johnson Media LLC");
Insert Into firms (name) values ("JPS Business Consulting");
Insert Into firms (name) values ("JR Solutions");
Insert Into firms (name) values ("JRC Consulting");
Insert Into firms (name) values ("JTSI");
Insert Into firms (name) values ("K2C Solutions");
Insert Into firms (name) values ("Kahle Consulting");
Insert Into firms (name) values ("KB Consulting");
Insert Into firms (name) values ("Kenneth Schieffer");
Insert Into firms (name) values ("KM Consulting");
Insert Into firms (name) values ("KMLogic Solutions");
Insert Into firms (name) values ("LB Consulting Services, LLC");
Insert Into firms (name) values ("Leadwell Solutions, LLC");
Insert Into firms (name) values ("Lede Business Consulting");
Insert Into firms (name) values ("Lighthouse Software, Inc.");
Insert Into firms (name) values ("Logicalis, Inc.");
Insert Into firms (name) values ("Maulee Tech LLC");
Insert Into firms (name) values ("Maya Enterprise Solutions");
Insert Into firms (name) values ("Meagon Knox");
Insert Into firms (name) values ("Micromaac");
Insert Into firms (name) values ("MIL Corporation");
Insert Into firms (name) values ("MJM Consulting");
Insert Into firms (name) values ("Modus Novus Inc");
Insert Into firms (name) values ("Montanus Consulting");
Insert Into firms (name) values ("Morgan Franklin");
Insert Into firms (name) values ("MTS, Inc");
Insert Into firms (name) values ("Multivision");
Insert Into firms (name) values ("MyConsultant.com");
Insert Into firms (name) values ("Mythics");
Insert Into firms (name) values ("NeatValue Solutions LLC");
Insert Into firms (name) values ("New Millennium Software LLC ");
Insert Into firms (name) values ("New Vendor Test");
Insert Into firms (name) values ("Nicole Merrill Consulting LLC");
Insert Into firms (name) values ("Northrop Grumman");
Insert Into firms (name) values ("Northwest Systems, LLC");
Insert Into firms (name) values ("NP Microsystems");
Insert Into firms (name) values ("NT Concepts");
Insert Into firms (name) values ("NTELX");
Insert Into firms (name) values ("Nuvista Technology Group");
Insert Into firms (name) values ("Old Dominion Solutions");
Insert Into firms (name) values ("O'Loughlin Ventures Inc.");
Insert Into firms (name) values ("Orion Solutions");
Insert Into firms (name) values ("Parc International INC");
Insert Into firms (name) values ("Platinum Training Solutions");
Insert Into firms (name) values ("PLM Solutions LLC");
Insert Into firms (name) values ("PoweredByLogic");
Insert Into firms (name) values ("Premios Consulting LLC");
Insert Into firms (name) values ("Price Waterhouse Cooper (PWC)");
Insert Into firms (name) values ("Prodigy Global Inc");
Insert Into firms (name) values ("Progressive Computer Tech");
Insert Into firms (name) values ("Pronghorn");
Insert Into firms (name) values ("Prudentra Inc");
Insert Into firms (name) values ("Quantam IT Solutions");
Insert Into firms (name) values ("Quest Associates");
Insert Into firms (name) values ("Rationale Technologies Corporation");
Insert Into firms (name) values ("Rebec LLC");
Insert Into firms (name) values ("Resource Thread LLC");
Insert Into firms (name) values ("Robert John Consultants inc.");
Insert Into firms (name) values ("Saber");
Insert Into firms (name) values ("Sage Solutions Consulting Inc");
Insert Into firms (name) values ("SAIC");
Insert Into firms (name) values ("Saicon Consultants");
Insert Into firms (name) values ("SAIINFOTECH, LLC");
Insert Into firms (name) values ("Sairav Consulting Inc");
Insert Into firms (name) values ("Saitech");
Insert Into firms (name) values ("SAP Star");
Insert Into firms (name) values ("Sapport Services LLC");
Insert Into firms (name) values ("Saqib Raja");
Insert Into firms (name) values ("SB Bus. Serv.");
Insert Into firms (name) values ("Serent Technologies");
Insert Into firms (name) values ("Serole Technologies");
Insert Into firms (name) values ("Sevatech");
Insert Into firms (name) values ("SGF Enterprises, LLC");
Insert Into firms (name) values ("Shashi Goyal");
Insert Into firms (name) values ("Shashi Goyal (1099)");
Insert Into firms (name) values ("Simpy FI-CO LLC");
Insert Into firms (name) values ("Siri Info Systems Inc");
Insert Into firms (name) values ("Softpro LLC");
Insert Into firms (name) values ("Spartacus");
Insert Into firms (name) values ("Sreesobhan");
Insert Into firms (name) values ("Starry Associates");
Insert Into firms (name) values ("Summit Consulting Group");
Insert Into firms (name) values ("Supani Inc.");
Insert Into firms (name) values ("SwiftVision Inc");
Insert Into firms (name) values ("Synchronicity Consulting");
Insert Into firms (name) values ("Tanzen LLC");
Insert Into firms (name) values ("Tech Analysis Inc");
Insert Into firms (name) values ("Technatomy");
Insert Into firms (name) values ("TechSuggest Inc.");
Insert Into firms (name) values ("Terathink");
Insert Into firms (name) values ("TKB Education Services");
Insert Into firms (name) values ("Transformation Consulting");
Insert Into firms (name) values ("Trilogy Federal");
Insert Into firms (name) values ("Tritus Technologies");
Insert Into firms (name) values ("TRS Consulting INC");
Insert Into firms (name) values ("Two95 International");
Insert Into firms (name) values ("Up & Away Advisors");
Insert Into firms (name) values ("Urban Miners");
Insert Into firms (name) values ("Vencore");
Insert Into firms (name) values ("Verbestel LLC");
Insert Into firms (name) values ("VML Consulting");
Insert Into firms (name) values ("W.R. Gothard and Associates Inc.");
Insert Into firms (name) values ("Williams Professional Computer Consulting");
Insert Into firms (name) values ("Zack Georgian Consulting");
Insert Into firms (name) values ("ZARSPOG Information Technology LLC");
