CREATE TABLE IF NOT EXISTS `opportunities` (
  `ID` mediumint UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `sub_client` mediumint UNSIGNED NOT NULL,
  `manager` mediumint UNSIGNED DEFAULT NULL,
  `stage` varchar(30) DEFAULT NULL,
  `gov_win_id` varchar(30) DEFAULT NULL,
  `fbo_link` varchar(200) DEFAULT NULL,
  `evaluation_criteria` varchar(1000) DEFAULT NULL,
  `win_themes` varchar(1000) DEFAULT NULL,
  `investment` varchar(1000) DEFAULT NULL,
  `pricing_strategy` varchar(1000) DEFAULT NULL,
  `award_type` varchar(30) DEFAULT NULL,
  `contract_type` varchar(30) DEFAULT NULL,
  `project_start_date` datetime DEFAULT NULL,
  `project_end_date` datetime DEFAULT NULL,
  `contract_value_total` int UNSIGNED DEFAULT NULL,
  `contract_value_expected` int UNSIGNED DEFAULT NULL,
  `win_probability` tinyint UNSIGNED DEFAULT NULL,
  `gov_win_link` varchar(200) DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `bp_budget_required` boolean DEFAULT NULL,
  `supporting_past_performance` boolean DEFAULT NULL,
  `price_to_win` boolean DEFAULT NULL,
  `team_assembled` boolean DEFAULT NULL,
  `credible_prime` boolean DEFAULT NULL,
  `priming_partner` mediumint UNSIGNED DEFAULT NULL,
  `contract_annual_value` int UNSIGNED DEFAULT NULL,
  `contract_even_distribution` boolean DEFAULT NULL,
  `aligned_to_solutions` boolean DEFAULT NULL,
  `price_competitive` boolean DEFAULT NULL,
  `last_updated_time` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_opportunities_manager` (`manager`),
  KEY `fk_opportunities_sub_client` (`sub_client`),
  KEY `fk_opportunities_firms_priming_partner` (`priming_partner`),
  CONSTRAINT `unique_opportunity` UNIQUE (`name`),
  CONSTRAINT `fk_opportunities_manager` FOREIGN KEY (`manager`) REFERENCES `people` (`ID`) ON DELETE SET NULL,
  CONSTRAINT `fk_opportunities_sub_client` FOREIGN KEY (`sub_client`) REFERENCES `sub_clients` (`ID`),
  CONSTRAINT `fk_opportunities_firms_priming_partner` FOREIGN KEY (`priming_partner`) REFERENCES `firms` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
