Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Millennial Media - M&A Consulting";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Research Administrative Management System (RAMS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CPSC Requirements Mgmt";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Data and Business Intelligence Support Services DBIS II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="MIDAS O&M PM";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="BI Phase 2";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="OUSD(I) SOA Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="CSG Executive Investment Board Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="ABP Production Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Medicaid Subject Matter Expert";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="KaBOOM! ERP/CRM Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="NRECA RS Platform Program";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CRM Roadmap";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CMS Provider Subject Matter Expert";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="SPAS Architecture Support";





Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="InterAmerican Bank SAP";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="IBM Tomlin SAP";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="ITDS Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Rules-based Architecture Solution";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Lease Management Opp";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Business Continuity Program Establishment";


Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="RS Redesign Usability Expert";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Processes Project - Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="NFL Mobile Integration with Verizon Wireless for Exclusive Content";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="BSS Release Management Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Project Canyon Project Management (2)";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="ePMO Lead (Sunrise / Payment Gateway)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="TS OASIS I";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CPSC - New System Development";


Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP CSPO Systems Engineering and/or Development";


Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast In-House FDW";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="SECURITY OPERATIONS CENTER SUPPORT SERVICES (SOC)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Medicare Master Data Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="RS Redesign Requirements Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Information Architecture - RS Program";


Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Project Wallace Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="BI Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Sunrise PMO - Add 1 Person";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Guided Event Management System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Processes Project - Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Process Project - Scoping and Analysis";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="SPAS - Q1 2012 Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="USE OF MOBILE DEVICES AND APPLICATIONS TO PROVIDE CUSTOMER SERVICE TO APPLICANTS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="STRATEGIC CONSULTING SERVICES FOR THE MANAGEMENT DIRECTORATE";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="9/11 Victims Compensation Fund";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="ACE Clarity";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="AESIP";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="AESIP PMO/IVV IBC";

Update tito.opportunities Set manager = (select ID from People where last_name = "Crumrine" and  first_name = "John") Where name="Application Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Sopko" and  first_name = "Lauren") Where name="Application Strategy & Development Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Army Logistics Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Attain DHS Mentor Protege";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Billing Program Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Crumrine" and  first_name = "John") Where name="Billing system software selection";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Boeing/NRO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Border Enforcement Management System";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="BSS Integration Office Staffing";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Cargo Systems PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Case Management Requirements Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP Wireless PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Central PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="CET Clarity Resource Mgmt Funct Deployment";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CIO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="CIS ITSSR Program Expansion";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS ITSSR Program Q1 2011";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS ITSSR Program Q2 2011";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS Transformation Q1 2011";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS Transformation Q2 2011";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS Transformation Q3 2011";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CIS Transformation Q4 2010";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Coast Guard - LIMS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CoE Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Consolidated Billing PII Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CPSC - EA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="CPSC Sol Arch/Bus Analyst";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="CSC USCIS SPAS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="CSC USCIS SPAS - 1Q 2012 growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CUSTOMER RELATIONSHIP MANAGEMENT SOFTWARE AND SUPPORTING SERVICES (CRM)";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="DHS HSIN PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="DHS Office of Human Capital IT";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="EAGLE II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="eBenefits Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ENCORE II DISA Task Order";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Enterprise Architecture Program Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ERP Analysis and SW Selection";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="ESDO TECHNICAL SUPPORT SERVICES";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="FBI ITSSS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Financial Sys PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Financials Systems IT Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="Ginnie Mae";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Google Apps Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="HHS UFMS Peoplesoft";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="HHS UFMS Peoplesoft - Phase II";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="ICE Small Business ID/IQ";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="iManage";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="IT Governance Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="IT Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="IT Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="ITSS-3";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="ITSS-4 Unisys";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Legacy System Migration/Integration Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="LIKELY CLOSE: Enterprise Services Governance Technical Support (ESG)";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="M&A PMO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="MIDAS - CSC";


Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="MIDAS TO3 Add-on";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="National Organic Program";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="NAVAIR ERP";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="NIH CIO SP-3";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="NIH CIO SP-3 SB";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="OASIS II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ODNI BTO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ODNI Fusion Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Crumrine" and  first_name = "John") Where name="Oracle R12 Upgrade/Re-Implement";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Our Daily Bread-";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Pension Benefits System - Program Planning";

Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Project Sunrise - Division Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Project Sunrise - Division UAT";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="SEVIS II";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="SM&G Build";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="SM&G Office - Pre Build-out";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="TABBS";

Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="TECS Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Testing & Release Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="TSA TTAC Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Usabllity Expert";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="USAID IT Forward";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="USCG PMO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="USCIS VIS Extension";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="USDA MIDAS TO3";

Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="VA Agent Orange Claims Processing Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="VA Agent Orange Claims Processing Support - Phase II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="VA innovation Initiative";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="VA VRM";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="VIS Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="VIS Recompete";

Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Wireless PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Service Management Assessment";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="GSA IB IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="OICO AWAC - Old Farm Application Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="PMSS-3";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Discovery and Document Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="FMMI Sustainment";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="USDA Financial Management and Internal Controls";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="USARCENT Financial Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="NFL Mobile - PM Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Sunrise PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast ePMO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="NFCU Data Mart";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Mobility Engineering";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="ARC Financial Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="AESIP GFEBS-SA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Surge .NET Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="BI Phase 2.x";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="BI Phase 3";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="DECC Program";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="CRM Project Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="CBP Finance Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="Gold Client - USDA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="COD Additional 100 Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP PS Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP FI/CO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP Basis Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="BI Data Warehouse Assessment";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Digitization and Content Management Implementation 2016";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="IV Case File Integration - ECM Pilot";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="EDSC OY2";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="DOI FBMS BIO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="TIPPS-4 OCIO PMSS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="IFS Re-Compete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="Army Financial Management and Audit";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Momentum Financials O&M";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="Strategic Asset Management Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP Support Project";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="Quality Management, Change Management and workflow Phase 2";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP Basis Outsourcing";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP FI/CO Project";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP PLM/SOLMAN Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Provider Enrollment, Chain and Ownership System (PECOS) Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Medicare Appeals System (O&M)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="LMP Trainers";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="MM Go-live support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="Janicki end user training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuler" and  first_name = "Fran") Where name="Eclipse Aerospace";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Agile Framework";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuler" and  first_name = "Fran") Where name="BOBJ Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Bristow" and  first_name = "Courtney") Where name="CFA Development Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Medicare Appeals System O&M Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast Agile Process Definition";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Payment Gateway Project Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="SAP Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="J6 Enterprise IT Solutions";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Individual Certification Programs (ICP) Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Strategic Partners Acquisition Readiness Contract (SPARC) IDIQ";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="FNS FMMI Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="API Project Center SharePoint Site";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="CSG Conversion Governance";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Project Oxygen Project Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="PACTS II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Army Enterprise Resource Planning Services (ERP)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Enterprise Resource Planning Independent Verification and Validation (ERP IV&V)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ICE Investigative Case Management TEC Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Global Combat Support System Army (GSS-A)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Information Technology Enterprise Solutions 3 Services (ITES-3 Chess)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Logistics Modernization Program (LMP)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="National Benefit Integrity Medicare Drug Integrity Contractor (NBI MEDIC)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Intelligence Statistical and Technical Analyses and Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Next Generation Enterprise Computing Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Business And Enterprise Service Technology II (BEST II)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Chief Information Officer Commodity Solutions (CIO-CS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Centralized Operations And Maintenance Information Technology Services (COMMIT)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="IT Support Services for Smart and Eciscor";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Agency For Health Care And Quality Applications Development Support Operations And Maintenace";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Healthcare Quality Information Systems (HCQIS) Adhoc Reports, Analytics, and Data Management (HCQISAR)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Analytical and Technical Support Services (NAC AND DFO)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Data Management (DM)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Sharepoint Integration and Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="SNAP Employment and Training Performance Tracking Software and Technical Assistance";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Veterans Relationship Management Program IT Solutions and Support (VRM)(ITSS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Revenue Modernization Collections and Financial System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Enterprise Testing Services Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Information Technology and Program Management Support Services for the Enterprise Performance Lifecycle (ITSS SDLC)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Enterprise Information Technology Solutions For the Software Engineering Center";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Security Technology Integrated Program Initiative (STIP)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Unified Case Management System (UCM)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Audit Accounting Compliance and Remediation Support for Office of Management and Budget A123 Requirements";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Financial Management Service Improvement";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Independent Verification and Validation Services (IV&V)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Financial Management Support Services for the Office of the Deputy Assistant Secretary of the Army for Cost and Economics (DASA-CE)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Project Portfolio Management System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="SBI Program Office Management Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Strategic Plan Analysis Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Automated Timber Sale Accounting System Redesign (ATSA)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Flexible Agile Development Services (FADS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Content Management Assessment Pilot";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="IRS OCFO recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="NAVY FIAR - FMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP CRM Project";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="CRM Project";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP End user training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Management Consulting Services for CFPB";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP Transformation and Service Management";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="Import Surveillance Program";

Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="SAP TMSS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="A123 Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast - TQM Environment Mgmt PM";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast - MOD Systems Integration PM";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="ERP 6 ehP6 Upgrade";
#Update tito.opportunities Set manager = (select ID from People where last_name = "Schuler" and  first_name = "Fran") Where name="BOBJ Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP 01 Training Onsite";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="JETS - Benefits";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="JETS - Risk and Fraud";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="VIS O&M";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="JETS - Records";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="ACE O&M";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="JETS - Customer Service";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="JETS - Biometrics";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Support for Platform Engineering and DEV-OPS Integration (SPEDI).";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="PM Portal 2.0";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="API SharePoint Support 2015";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS Sustainment Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Army Contract Writing System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Army SAP01 at Picatinny";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="ALLIANT 2 Unrestricted";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="FSSP IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="Personas Implementation and Portal Redesign";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="Innovation Lab - Operational Improvement and Issue Resolution";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="ABCO Interface Re-write";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="FMMI Issue Management and Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="Continued Flex Training";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="WB-SCM Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Maguire" and  first_name = "Dan") Where name="MIDAS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="FMMI Re-Compete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Alchemy Pilot";
Update tito.opportunities Set manager = (select ID from People where last_name = "Roden" and  first_name = "JC") Where name="SAP Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="IRS IFS Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Costello" and  first_name = "Joe") Where name="BI Platform Mgmt Assess";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="Financial Management Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="ECM Next Generation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="GSA Transportation Audit Business Review";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast -  TWC Billing PMO Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast - CSG APC Billing Analyst";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast - TWC Deal Workstream PM";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="SAP IV&V Data Audit";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="DATA AND INFORMATION MANAGEMENT MISSION SUPPORT";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="ARMY CONTRACT WRITING SYSTEM (ACWS)";


Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Integrated Traveler Initiative (ITI)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="TECHNICAL AND PROGRAM MANAGEMENT SUPPORT SERVICES FOR THE ARMY NATIONAL GUARD (TPMSS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="ENTERPRISE ARCHITECTURE PROGRAM SUPPORT SERVICES";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="FARM LOAN PROGRAM INFORMATION DELIVERY SYSTEM FOLLOW ON (FLPIDS)";

Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GLOBAL COMBAT SUPPORT SYSTEM ARMY (GCSS-A)";


Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="FINANCIAL MANAGEMENT SUPPORT SERVICES";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="FINANCIAL MANAGEMENT COMPUTER SOFTWARE CONSULTING SERVICES (FM)";


Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast Spectacor - Digitial Services PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="Comcast - CSG Golden Configuration Governance";
Update tito.opportunities Set manager = (select ID from People where last_name = "McGovern" and  first_name = "Jonathan") Where name="AARP - RFP Development";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="CRM/SharePoint Integration";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="2016 SharePoint Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VA Adv - TOPR 2 - Compliance/Risk";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VA Adv - TOPR 3 - Empl Engagement";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VA Adv - TOPR 7 - TMS transition support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VA ADV - Add'l TOPRs";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VA Adv - TOPR 16 - EDM Biz Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="USDA PACA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="Financial Management & Admin Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="PM AESIP PMO";
Update tito.opportunities Set manager = (select ID from People where last_name = "Foley" and  first_name = "J.P.") Where name="NAVY PIRMDS2";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="NAVY - FIP";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="GSA 18F Phase I";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="GSA - 18F - PII";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="GSA Pegasus Testing Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="FADS Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="TYAD LMP and PMO Support - Recompete";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="US Army TMSS Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Campbell" and  first_name = "Howard") Where name="DLA Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Levitan" and  first_name = "Jim") Where name="IRS Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="PSPD Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Bristow" and  first_name = "Courtney") Where name="CSPC Organic Growth";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="GSA/USDA - USIP IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Software Development and Integration Full and Open (SDING2)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="DLA J8 SAP Upgrade";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Pipeline Knowledge Learning Portal";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="Microstrategy Office 365 Migration";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP TASPD Business Intelligence Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Army Contract Writing System (ACWS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="IV Modernization Cloud Migration";

Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="FADS Organic Growth 2016";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="EDMS Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="IVCS Extension";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="TruGreen - Scotts Integration Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Enterprise Business Objects";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="API IT Change Management System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA APHIS SharePoint Assessment and Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Enforcement O&M - Agile";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="SETA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="Agile IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="Army PMSS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="FIPS Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="CIOSP-3";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="ENCORE";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hart" and  first_name = "Laurence") Where name="ICAT (Correspondence and Tasking System)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="EDSC II";

Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS Functional Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="TASPD O&M";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP Biometric Exit";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="USACE Property Management System Study";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="MSIX IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="EPA - ITS-BISS III";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="TSA IMPACT";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hart" and  first_name = "Laurence") Where name="Library of Congress - USCO Recordation Modernization";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="Nevada CES IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Price and Credit Task Order";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="Program Management Office Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="Financial Management Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Library Financial Management System Assessment";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS Real Property Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="VA IV&V Discovery Phase";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Agile Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="EPA Compass Hosting and Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="USDA > SSLOBS > Shared Service Line Of Business Services BPA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="TIM Agile Design and Development Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS Increment II";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="Agile Application Development Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="IT SYSTEMS DEVELOPMENT AND MAINTENANCE RETIREMENT AND BENEFITS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="APPLICATIONS DEVELOPMENT ENGINEERING AND SUSTAINMENT (EADIS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > OCFO > Shared Service Company Code Retrofit";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > FS > SAP Automated Testing for Regression";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > SSLOBS Task Order > FEMA Grants Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > SSLOBS Task Order > FEMA Financial Shared Service Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Carr" and  first_name = "Jedediah") Where name="API Web Content Review and Strategy";
Update tito.opportunities Set manager = (select ID from People where last_name = "Barber" and  first_name = "Todd") Where name="USDA > Incident Management > OY2 Run Rate";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA FS RBAA Extension / New Requirements";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="TRANSFORMATION INTEGRATION AND CONFIGURATION SERVICES (TICS)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Services for Enabling Agile Delivery (SEAD)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="Joint Engineering Teams – Sustainment of (JETS) Business Support Services (BSS) III";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="Grants.gov Managed Package Extension";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Incident Mgt > Data Act Cost Accounting Updates";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Incident Management > OY3 Run Rate";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Incident Management > OY4 Run Rate";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Relocation Follow On Work";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Data Act > ARS Cost Allocation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > FS > RBAA > Follow On Work";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Grants.gov Migrate Interfaces from PI to Mulesoft";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > 2017 Training Upsell";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > User Experience (Fiori / Personas)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="USDA > Shared Service VA Migration (OY4)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Duffy" and  first_name = "Matthew") Where name="USDA > Pegasys Support (FY18)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Gold" and  first_name = "Scott") Where name="LoC LBFMS Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Schuerhoff" and  first_name = "Todd") Where name="FADS 2 Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="General Technical and Financial Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="IT Support BPA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="Financial Management SaaS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="Travel Integration and Data Standards Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="VECTOR";
Update tito.opportunities Set manager = (select ID from People where last_name = "Bristow" and  first_name = "Courtney") Where name="Event Management System";
Update tito.opportunities Set manager = (select ID from People where last_name = "Lyle" and  first_name = "Glen") Where name="CBP EDME Data Center Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > OCFO > SAP and Mulesoft Support of OMS";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > OCFO > SAP and Mulesoft Follow On Support (Part 2)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Migration to Suite on HANA";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="LMP Red River Site Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="DLA Distribution Modernization Program Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="Army LMP Sustainment Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Hagstoz" and  first_name = "George") Where name="GFEBS-SA Support";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > SSLOBS > Task Order 1 - Financials";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > SSLOBS > Task Order 2 - HR";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Grants >  NIFA Grants Enhancements";
Update tito.opportunities Set manager = (select ID from People where last_name = "Spadafore" and  first_name = "Tim") Where name="Financial and Business Management System Support Services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Gold" and  first_name = "Scott") Where name="NSF Performance Reporting IV&V";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="Software as a Service (SaaS) applications/services";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="NRCS Blanket IT BPA (Pega / SNOW / Other)";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Incident Management > Data Act Cost Assessment Implementation";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Grants > FEMA Mini Release 2";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > MIDAS SAP and Cotton Systems > CIOSP3 Small - AG-3144-S-17-0015";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > MIDAS > CIOSP3 > Price Support, Conservation System, Subsidy/Disaster, Acreage and Common Farm.";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > Relocation Extension 2017 July";
Update tito.opportunities Set manager = (select ID from People where last_name = "Vaughan" and  first_name = "Geoff") Where name="USDA > NIFA Formula Grants";
